DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  avatar TEXT,
  date TIMESTAMP DEFAULT now() NOT NULL,
  company TEXT,
  website TEXT,
  location TEXT,
  bio TEXT,
  twitter_url TEXT, 
  facebook_url TEXT, 
  youtube_url TEXT, 
  linkedin_url TEXT, 
  instagram_url TEXT 
);

CREATE TABLE post ( 
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   users integer references users(id) NOT NULL,
  post TEXT NOT NULL, 
  avatar TEXT,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);