DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  avatar TEXT,
  date TIMESTAMP DEFAULT now() NOT NULL,
  company TEXT,
  website TEXT,
  location TEXT,
  status TEXT,
  bio TEXT,
  school TEXT
);