CREATE TABLE profile (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company TEXT,
    website TEXT,
    location TEXT,
    status TEXT NOT NULL,
    skills TEXT NOT NULL,
    bio TEXT,
    githubusername TEXT UNIQUE
)